#!/bin/tcsh
#PBS -N lcV
#PBS -l nodes=5:vortex:ppn=12
#PBS -l walltime=48:00:00
#PBS -j oe


# init conda within new shell for job
source "/usr/local/anaconda3-2021.05/etc/profile.d/conda.csh"
module load anaconda3/2021.05
module load openmpi/3.1.4/gcc-9.3.0
unsetenv PYTHONPATH
conda activate gee


mpiexec -np 60 python /sciclone/home20/hmbaier/temporal_mex/dl.py > /sciclone/home20/hmbaier/temporal_mex/main_log_0713.txt
